{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ElepayCardBridge"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/elepaysdk\/elepaycardbridge"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/elepaysdk\/elepaycardbridge"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/jp.elestyle.Elepay\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/jp.elestyle.Elepay\/objc(pl)NSObject","doc:\/\/jp.elestyle.Elepay\/s7CVarArgP","doc:\/\/jp.elestyle.Elepay\/s28CustomDebugStringConvertibleP","doc:\/\/jp.elestyle.Elepay\/s23CustomStringConvertibleP","doc:\/\/jp.elestyle.Elepay\/SQ","doc:\/\/jp.elestyle.Elepay\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayCardBridge","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayCardBridge\/address","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayCardBridge\/currency","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayCardBridge\/cvc","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayCardBridge\/expMonth","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayCardBridge\/expYear","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayCardBridge\/name","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayCardBridge\/number"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ElepayCardBridge"}],"title":"ElepayCardBridge","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)ElepayCardBridge","modules":[{"name":"ElepaySDK"}],"navigatorTitle":[{"kind":"identifier","text":"ElepayCardBridge"}]},"hierarchy":{"paths":[["doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK"]]},"seeAlsoSections":[{"title":"3rd party framework bridge","identifiers":["doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayChinesePaymentsBridge","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayStripeBridge","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/StripeBridgeCardValidationState","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/StripeBridgePaymentStatus","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayRPayBridge","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ApplePayContextDelegateBridge"],"generated":true}],"references":{"doc://jp.elestyle.Elepay/documentation/ElepaySDK/ElepayStripeBridge":{"role":"symbol","title":"ElepayStripeBridge","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ElepayStripeBridge"}],"abstract":[],"identifier":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayStripeBridge","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ElepayStripeBridge"}],"url":"\/documentation\/elepaysdk\/elepaystripebridge"},"doc://jp.elestyle.Elepay/documentation/ElepaySDK/StripeBridgePaymentStatus":{"role":"symbol","title":"StripeBridgePaymentStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"StripeBridgePaymentStatus"}],"abstract":[],"identifier":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/StripeBridgePaymentStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StripeBridgePaymentStatus"}],"url":"\/documentation\/elepaysdk\/stripebridgepaymentstatus"},"doc://jp.elestyle.Elepay/documentation/ElepaySDK/ElepayCardBridge":{"role":"symbol","title":"ElepayCardBridge","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ElepayCardBridge"}],"abstract":[],"identifier":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayCardBridge","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ElepayCardBridge"}],"url":"\/documentation\/elepaysdk\/elepaycardbridge"},"doc://jp.elestyle.Elepay/documentation/ElepaySDK/ElepayRPayBridge":{"role":"symbol","title":"ElepayRPayBridge","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ElepayRPayBridge"}],"abstract":[],"identifier":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayRPayBridge","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ElepayRPayBridge"}],"url":"\/documentation\/elepaysdk\/elepayrpaybridge"},"doc://jp.elestyle.Elepay/documentation/ElepaySDK/StripeBridgeCardValidationState":{"role":"symbol","title":"StripeBridgeCardValidationState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"StripeBridgeCardValidationState"}],"abstract":[],"identifier":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/StripeBridgeCardValidationState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StripeBridgeCardValidationState"}],"url":"\/documentation\/elepaysdk\/stripebridgecardvalidationstate"},"doc://jp.elestyle.Elepay/documentation/ElepaySDK/ElepayCardBridge/currency":{"role":"symbol","title":"currency","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"currency"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayCardBridge\/currency","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"currency"}],"url":"\/documentation\/elepaysdk\/elepaycardbridge\/currency"},"doc://jp.elestyle.Elepay/documentation/ElepaySDK":{"role":"collection","title":"ElepaySDK","abstract":[{"type":"text","text":"elepay SDK for iOS is made for your iOS \/ iPad OS Apps to easily import elepay multi-payment platform."}],"identifier":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK","kind":"symbol","type":"topic","url":"\/documentation\/elepaysdk"},"doc://jp.elestyle.Elepay/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/jp.elestyle.Elepay\/s23CustomStringConvertibleP"},"doc://jp.elestyle.Elepay/documentation/ElepaySDK/ElepayChinesePaymentsBridge":{"role":"symbol","title":"ElepayChinesePaymentsBridge","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ElepayChinesePaymentsBridge"}],"abstract":[],"identifier":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayChinesePaymentsBridge","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ElepayChinesePaymentsBridge"}],"url":"\/documentation\/elepaysdk\/elepaychinesepaymentsbridge"},"doc://jp.elestyle.Elepay/documentation/ElepaySDK/ElepayCardBridge/name":{"role":"symbol","title":"name","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayCardBridge\/name","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"name"}],"url":"\/documentation\/elepaysdk\/elepaycardbridge\/name"},"doc://jp.elestyle.Elepay/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/jp.elestyle.Elepay\/objc(cs)NSObject"},"doc://jp.elestyle.Elepay/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/jp.elestyle.Elepay\/SQ"},"doc://jp.elestyle.Elepay/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/jp.elestyle.Elepay\/s7CVarArgP"},"doc://jp.elestyle.Elepay/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/jp.elestyle.Elepay\/objc(pl)NSObject"},"doc://jp.elestyle.Elepay/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/jp.elestyle.Elepay\/SH"},"doc://jp.elestyle.Elepay/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/jp.elestyle.Elepay\/s28CustomDebugStringConvertibleP"},"doc://jp.elestyle.Elepay/documentation/ElepaySDK/ElepayCardBridge/cvc":{"role":"symbol","title":"cvc","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cvc"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayCardBridge\/cvc","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"cvc"}],"url":"\/documentation\/elepaysdk\/elepaycardbridge\/cvc"},"doc://jp.elestyle.Elepay/documentation/ElepaySDK/ApplePayContextDelegateBridge":{"role":"symbol","title":"ApplePayContextDelegateBridge","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ApplePayContextDelegateBridge"}],"abstract":[],"identifier":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ApplePayContextDelegateBridge","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ApplePayContextDelegateBridge"}],"url":"\/documentation\/elepaysdk\/applepaycontextdelegatebridge"},"doc://jp.elestyle.Elepay/documentation/ElepaySDK/ElepayCardBridge/address":{"role":"symbol","title":"address","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"address"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayCardBridge\/address","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"address"}],"url":"\/documentation\/elepaysdk\/elepaycardbridge\/address"},"doc://jp.elestyle.Elepay/documentation/ElepaySDK/ElepayCardBridge/expYear":{"role":"symbol","title":"expYear","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"expYear"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[],"identifier":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayCardBridge\/expYear","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"expYear"}],"url":"\/documentation\/elepaysdk\/elepaycardbridge\/expyear"},"doc://jp.elestyle.Elepay/documentation/ElepaySDK/ElepayCardBridge/expMonth":{"role":"symbol","title":"expMonth","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"expMonth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[],"identifier":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayCardBridge\/expMonth","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"expMonth"}],"url":"\/documentation\/elepaysdk\/elepaycardbridge\/expmonth"},"doc://jp.elestyle.Elepay/documentation/ElepaySDK/ElepayCardBridge/number":{"role":"symbol","title":"number","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"number"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayCardBridge\/number","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"number"}],"url":"\/documentation\/elepaysdk\/elepaycardbridge\/number"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ElepayCardBridge"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ElepayCardBridge"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ElepayCardBridge"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayCardBridge\/address","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayCardBridge\/currency","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayCardBridge\/cvc","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayCardBridge\/expMonth","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayCardBridge\/expYear","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayCardBridge\/name","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayCardBridge\/number"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/jp.elestyle.Elepay\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"3rd party framework bridge","identifiers":["doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayChinesePaymentsBridge","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayStripeBridge","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/StripeBridgeCardValidationState","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/StripeBridgePaymentStatus","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayRPayBridge","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ApplePayContextDelegateBridge"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ElepayCardBridge"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayStripeBridge\/title","value":"ElepayStripeBridge"},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayStripeBridge\/fragments","value":[{"kind":"identifier","text":"ElepayStripeBridge"}]},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1StripeBridgePaymentStatus\/title","value":"StripeBridgePaymentStatus"},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1StripeBridgePaymentStatus\/fragments","value":[{"kind":"identifier","text":"StripeBridgePaymentStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayCardBridge\/title","value":"ElepayCardBridge"},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayCardBridge\/fragments","value":[{"kind":"identifier","text":"ElepayCardBridge"}]},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayRPayBridge\/title","value":"ElepayRPayBridge"},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayRPayBridge\/fragments","value":[{"kind":"identifier","text":"ElepayRPayBridge"}]},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1StripeBridgeCardValidationState\/title","value":"StripeBridgeCardValidationState"},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1StripeBridgeCardValidationState\/fragments","value":[{"kind":"identifier","text":"StripeBridgeCardValidationState"}]},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayCardBridge~1currency\/title","value":"currency"},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayCardBridge~1currency\/fragments","value":[{"kind":"identifier","text":"currency"}]},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayChinesePaymentsBridge\/title","value":"ElepayChinesePaymentsBridge"},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayChinesePaymentsBridge\/fragments","value":[{"kind":"identifier","text":"ElepayChinesePaymentsBridge"}]},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayCardBridge~1name\/title","value":"name"},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayCardBridge~1name\/fragments","value":[{"kind":"identifier","text":"name"}]},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayCardBridge~1cvc\/title","value":"cvc"},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayCardBridge~1cvc\/fragments","value":[{"kind":"identifier","text":"cvc"}]},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ApplePayContextDelegateBridge\/title","value":"ApplePayContextDelegateBridge"},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ApplePayContextDelegateBridge\/fragments","value":[{"kind":"identifier","text":"ApplePayContextDelegateBridge"}]},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayCardBridge~1address\/title","value":"address"},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayCardBridge~1address\/fragments","value":[{"kind":"identifier","text":"address"}]},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayCardBridge~1expYear\/title","value":"expYear"},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayCardBridge~1expYear\/fragments","value":[{"kind":"identifier","text":"expYear"}]},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayCardBridge~1expMonth\/title","value":"expMonth"},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayCardBridge~1expMonth\/fragments","value":[{"kind":"identifier","text":"expMonth"}]},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayCardBridge~1number\/title","value":"number"},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayCardBridge~1number\/fragments","value":[{"kind":"identifier","text":"number"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}