{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ElepayRPayBridge"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/elepaysdk\/elepayrpaybridge"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/elepaysdk\/elepayrpaybridge"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/jp.elestyle.Elepay\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/jp.elestyle.Elepay\/objc(pl)NSObject","doc:\/\/jp.elestyle.Elepay\/s7CVarArgP","doc:\/\/jp.elestyle.Elepay\/s28CustomDebugStringConvertibleP","doc:\/\/jp.elestyle.Elepay\/s23CustomStringConvertibleP","doc:\/\/jp.elestyle.Elepay\/SQ","doc:\/\/jp.elestyle.Elepay\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayRPayBridge","interfaceLanguage":"swift"},"topicSections":[{"title":"Type Methods","identifiers":["doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayRPayBridge\/safeRPayClientClass()"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ElepayRPayBridge"}],"title":"ElepayRPayBridge","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)ElepayRPayBridge","modules":[{"name":"ElepaySDK"}],"navigatorTitle":[{"kind":"identifier","text":"ElepayRPayBridge"}]},"hierarchy":{"paths":[["doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK"]]},"seeAlsoSections":[{"title":"3rd party framework bridge","identifiers":["doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayChinesePaymentsBridge","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayStripeBridge","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/StripeBridgeCardValidationState","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/StripeBridgePaymentStatus","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayCardBridge","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ApplePayContextDelegateBridge"],"generated":true}],"references":{"doc://jp.elestyle.Elepay/documentation/ElepaySDK/StripeBridgeCardValidationState":{"role":"symbol","title":"StripeBridgeCardValidationState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"StripeBridgeCardValidationState"}],"abstract":[],"identifier":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/StripeBridgeCardValidationState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StripeBridgeCardValidationState"}],"url":"\/documentation\/elepaysdk\/stripebridgecardvalidationstate"},"doc://jp.elestyle.Elepay/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/jp.elestyle.Elepay\/s7CVarArgP"},"doc://jp.elestyle.Elepay/documentation/ElepaySDK/ApplePayContextDelegateBridge":{"role":"symbol","title":"ApplePayContextDelegateBridge","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ApplePayContextDelegateBridge"}],"abstract":[],"identifier":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ApplePayContextDelegateBridge","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ApplePayContextDelegateBridge"}],"url":"\/documentation\/elepaysdk\/applepaycontextdelegatebridge"},"doc://jp.elestyle.Elepay/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/jp.elestyle.Elepay\/SQ"},"doc://jp.elestyle.Elepay/documentation/ElepaySDK/ElepayRPayBridge/safeRPayClientClass()":{"role":"symbol","title":"safeRPayClientClass()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"safeRPayClientClass"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"AnyClass","preciseIdentifier":"s:s8AnyClassa"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayRPayBridge\/safeRPayClientClass()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"safeRPayClientClass"}],"url":"\/documentation\/elepaysdk\/elepayrpaybridge\/saferpayclientclass()"},"doc://jp.elestyle.Elepay/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/jp.elestyle.Elepay\/s23CustomStringConvertibleP"},"doc://jp.elestyle.Elepay/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/jp.elestyle.Elepay\/SH"},"doc://jp.elestyle.Elepay/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/jp.elestyle.Elepay\/s28CustomDebugStringConvertibleP"},"doc://jp.elestyle.Elepay/documentation/ElepaySDK/ElepayStripeBridge":{"role":"symbol","title":"ElepayStripeBridge","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ElepayStripeBridge"}],"abstract":[],"identifier":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayStripeBridge","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ElepayStripeBridge"}],"url":"\/documentation\/elepaysdk\/elepaystripebridge"},"doc://jp.elestyle.Elepay/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/jp.elestyle.Elepay\/objc(cs)NSObject"},"doc://jp.elestyle.Elepay/documentation/ElepaySDK/StripeBridgePaymentStatus":{"role":"symbol","title":"StripeBridgePaymentStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"StripeBridgePaymentStatus"}],"abstract":[],"identifier":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/StripeBridgePaymentStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StripeBridgePaymentStatus"}],"url":"\/documentation\/elepaysdk\/stripebridgepaymentstatus"},"doc://jp.elestyle.Elepay/documentation/ElepaySDK/ElepayChinesePaymentsBridge":{"role":"symbol","title":"ElepayChinesePaymentsBridge","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ElepayChinesePaymentsBridge"}],"abstract":[],"identifier":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayChinesePaymentsBridge","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ElepayChinesePaymentsBridge"}],"url":"\/documentation\/elepaysdk\/elepaychinesepaymentsbridge"},"doc://jp.elestyle.Elepay/documentation/ElepaySDK/ElepayRPayBridge":{"role":"symbol","title":"ElepayRPayBridge","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ElepayRPayBridge"}],"abstract":[],"identifier":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayRPayBridge","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ElepayRPayBridge"}],"url":"\/documentation\/elepaysdk\/elepayrpaybridge"},"doc://jp.elestyle.Elepay/documentation/ElepaySDK/ElepayCardBridge":{"role":"symbol","title":"ElepayCardBridge","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ElepayCardBridge"}],"abstract":[],"identifier":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayCardBridge","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ElepayCardBridge"}],"url":"\/documentation\/elepaysdk\/elepaycardbridge"},"doc://jp.elestyle.Elepay/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/jp.elestyle.Elepay\/objc(pl)NSObject"},"doc://jp.elestyle.Elepay/documentation/ElepaySDK":{"role":"collection","title":"ElepaySDK","abstract":[{"type":"text","text":"elepay SDK for iOS is made for your iOS \/ iPad OS Apps to easily import elepay multi-payment platform."}],"identifier":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK","kind":"symbol","type":"topic","url":"\/documentation\/elepaysdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ElepayRPayBridge"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ElepayRPayBridge"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ElepayRPayBridge"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Type Methods","identifiers":["doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayRPayBridge\/safeRPayClientClass()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/jp.elestyle.Elepay\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"3rd party framework bridge","identifiers":["doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayChinesePaymentsBridge","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayStripeBridge","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/StripeBridgeCardValidationState","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/StripeBridgePaymentStatus","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayCardBridge","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ApplePayContextDelegateBridge"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ElepayRPayBridge"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1StripeBridgeCardValidationState\/title","value":"StripeBridgeCardValidationState"},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1StripeBridgeCardValidationState\/fragments","value":[{"kind":"identifier","text":"StripeBridgeCardValidationState"}]},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ApplePayContextDelegateBridge\/title","value":"ApplePayContextDelegateBridge"},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ApplePayContextDelegateBridge\/fragments","value":[{"kind":"identifier","text":"ApplePayContextDelegateBridge"}]},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayRPayBridge~1safeRPayClientClass()\/title","value":"safeRPayClientClass"},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayRPayBridge~1safeRPayClientClass()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"safeRPayClientClass"}]},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayStripeBridge\/title","value":"ElepayStripeBridge"},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayStripeBridge\/fragments","value":[{"kind":"identifier","text":"ElepayStripeBridge"}]},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1StripeBridgePaymentStatus\/title","value":"StripeBridgePaymentStatus"},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1StripeBridgePaymentStatus\/fragments","value":[{"kind":"identifier","text":"StripeBridgePaymentStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayChinesePaymentsBridge\/title","value":"ElepayChinesePaymentsBridge"},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayChinesePaymentsBridge\/fragments","value":[{"kind":"identifier","text":"ElepayChinesePaymentsBridge"}]},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayRPayBridge\/title","value":"ElepayRPayBridge"},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayRPayBridge\/fragments","value":[{"kind":"identifier","text":"ElepayRPayBridge"}]},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayCardBridge\/title","value":"ElepayCardBridge"},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayCardBridge\/fragments","value":[{"kind":"identifier","text":"ElepayCardBridge"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}