{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"ElepayVersionNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/elepaysdk\/elepayversionnumber"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/elepaysdk\/elepayversionnumber"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayVersionNumber","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Project version number for Elepay."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"ElepayVersionNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"title":"ElepayVersionNumber","roleHeading":"Global Variable","role":"symbol","symbolKind":"var","externalID":"c:@ElepayVersionNumber","modules":[{"name":"ElepaySDK"}],"navigatorTitle":[{"kind":"identifier","text":"ElepayVersionNumber"}]},"hierarchy":{"paths":[["doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK"]]},"references":{"doc://jp.elestyle.Elepay/documentation/ElepaySDK/ElepayVersionNumber":{"role":"symbol","title":"ElepayVersionNumber","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"ElepayVersionNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"Project version number for Elepay."}],"identifier":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayVersionNumber","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ElepayVersionNumber"}],"url":"\/documentation\/elepaysdk\/elepayversionnumber"},"doc://jp.elestyle.Elepay/documentation/ElepaySDK":{"role":"collection","title":"ElepaySDK","abstract":[{"type":"text","text":"elepay SDK for iOS is made for your iOS \/ iPad OS Apps to easily import elepay multi-payment platform."}],"identifier":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK","kind":"symbol","type":"topic","url":"\/documentation\/elepaysdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Global Variable"},{"op":"replace","path":"\/metadata\/title","value":"ElepayVersionNumber"},{"op":"replace","path":"\/metadata\/symbolKind","value":"var"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ElepayVersionNumber"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":" "},{"kind":"identifier","text":"ElepayVersionNumber"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayVersionNumber\/title","value":"ElepayVersionNumber"},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayVersionNumber\/fragments","value":[{"kind":"identifier","text":"ElepayVersionNumber"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}