{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ElepayChinesePaymentsBridge"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/elepaysdk\/elepaychinesepaymentsbridge"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/elepaysdk\/elepaychinesepaymentsbridge"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/jp.elestyle.Elepay\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/jp.elestyle.Elepay\/objc(pl)NSObject","doc:\/\/jp.elestyle.Elepay\/s7CVarArgP","doc:\/\/jp.elestyle.Elepay\/s28CustomDebugStringConvertibleP","doc:\/\/jp.elestyle.Elepay\/s23CustomStringConvertibleP","doc:\/\/jp.elestyle.Elepay\/SQ","doc:\/\/jp.elestyle.Elepay\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayChinesePaymentsBridge","interfaceLanguage":"swift"},"topicSections":[{"title":"Type Methods","identifiers":["doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayChinesePaymentsBridge\/handleUPOpen(_:complete:)","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayChinesePaymentsBridge\/handleWXOpen(_:)","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayChinesePaymentsBridge\/handleWXOpenUniversalLink(_:)","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayChinesePaymentsBridge\/isAlipayAvailable()","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayChinesePaymentsBridge\/isAllpaySDKAvailable()","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayChinesePaymentsBridge\/isUPAppInstalled()","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayChinesePaymentsBridge\/isUnionPaySDKAvailable()","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayChinesePaymentsBridge\/isWXAppInstalled()","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayChinesePaymentsBridge\/isWXAppSupportAPI()","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayChinesePaymentsBridge\/isWechatPayAvailable()","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayChinesePaymentsBridge\/makeWXPayment(_:callback:)","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayChinesePaymentsBridge\/open(_:)","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayChinesePaymentsBridge\/pay(_:mode:scheme:viewController:onResult:)","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayChinesePaymentsBridge\/payOrder(withPayload:fromScheme:callback:)","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayChinesePaymentsBridge\/processAuth_V2Result(withResultUrl:standbyCallback:)","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayChinesePaymentsBridge\/processOrder(withPaymentResult:standbyCallback:)","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayChinesePaymentsBridge\/registerWXApp(_:universalLink:)","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayChinesePaymentsBridge\/startUPPayment(_:fromScheme:mode:viewController:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ElepayChinesePaymentsBridge"}],"title":"ElepayChinesePaymentsBridge","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)ElepayChinesePaymentsBridge","modules":[{"name":"ElepaySDK"}],"navigatorTitle":[{"kind":"identifier","text":"ElepayChinesePaymentsBridge"}]},"hierarchy":{"paths":[["doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK"]]},"seeAlsoSections":[{"title":"3rd party framework bridge","identifiers":["doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayStripeBridge","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/StripeBridgeCardValidationState","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/StripeBridgePaymentStatus","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayRPayBridge","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayCardBridge","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ApplePayContextDelegateBridge"],"generated":true}],"references":{"doc://jp.elestyle.Elepay/documentation/ElepaySDK":{"role":"collection","title":"ElepaySDK","abstract":[{"type":"text","text":"elepay SDK for iOS is made for your iOS \/ iPad OS Apps to easily import elepay multi-payment platform."}],"identifier":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK","kind":"symbol","type":"topic","url":"\/documentation\/elepaysdk"},"doc://jp.elestyle.Elepay/documentation/ElepaySDK/ElepayChinesePaymentsBridge/handleWXOpen(_:)":{"role":"symbol","title":"handleWXOpen(_:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handleWXOpen"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayChinesePaymentsBridge\/handleWXOpen(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"handleWXOpenURL:"}],"url":"\/documentation\/elepaysdk\/elepaychinesepaymentsbridge\/handlewxopen(_:)"},"doc://jp.elestyle.Elepay/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/jp.elestyle.Elepay\/s28CustomDebugStringConvertibleP"},"doc://jp.elestyle.Elepay/documentation/ElepaySDK/ElepayChinesePaymentsBridge/isWXAppSupportAPI()":{"role":"symbol","title":"isWXAppSupportAPI()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isWXAppSupportAPI"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayChinesePaymentsBridge\/isWXAppSupportAPI()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isWXAppSupportAPI"}],"url":"\/documentation\/elepaysdk\/elepaychinesepaymentsbridge\/iswxappsupportapi()"},"doc://jp.elestyle.Elepay/documentation/ElepaySDK/ElepayChinesePaymentsBridge/makeWXPayment(_:callback:)":{"role":"symbol","title":"makeWXPayment(_:callback:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"makeWXPayment"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"callback"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayChinesePaymentsBridge\/makeWXPayment(_:callback:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"makeWXPayment:callback:"}],"url":"\/documentation\/elepaysdk\/elepaychinesepaymentsbridge\/makewxpayment(_:callback:)"},"doc://jp.elestyle.Elepay/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/jp.elestyle.Elepay\/s23CustomStringConvertibleP"},"doc://jp.elestyle.Elepay/documentation/ElepaySDK/ElepayChinesePaymentsBridge":{"role":"symbol","title":"ElepayChinesePaymentsBridge","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ElepayChinesePaymentsBridge"}],"abstract":[],"identifier":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayChinesePaymentsBridge","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ElepayChinesePaymentsBridge"}],"url":"\/documentation\/elepaysdk\/elepaychinesepaymentsbridge"},"doc://jp.elestyle.Elepay/documentation/ElepaySDK/ElepayChinesePaymentsBridge/isAllpaySDKAvailable()":{"role":"symbol","title":"isAllpaySDKAvailable()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isAllpaySDKAvailable"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayChinesePaymentsBridge\/isAllpaySDKAvailable()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isAllpaySDKAvailable"}],"url":"\/documentation\/elepaysdk\/elepaychinesepaymentsbridge\/isallpaysdkavailable()"},"doc://jp.elestyle.Elepay/documentation/ElepaySDK/ElepayChinesePaymentsBridge/open(_:)":{"role":"symbol","title":"open(_:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"open"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayChinesePaymentsBridge\/open(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"openURL:"}],"url":"\/documentation\/elepaysdk\/elepaychinesepaymentsbridge\/open(_:)"},"doc://jp.elestyle.Elepay/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/jp.elestyle.Elepay\/SH"},"doc://jp.elestyle.Elepay/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/jp.elestyle.Elepay\/s7CVarArgP"},"doc://jp.elestyle.Elepay/documentation/ElepaySDK/ElepayChinesePaymentsBridge/payOrder(withPayload:fromScheme:callback:)":{"role":"symbol","title":"payOrder(withPayload:fromScheme:callback:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"payOrder"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withPayload"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"fromScheme"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"callback"},{"kind":"text","text":": (["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayChinesePaymentsBridge\/payOrder(withPayload:fromScheme:callback:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"payOrderWithPayload:fromScheme:callback:"}],"url":"\/documentation\/elepaysdk\/elepaychinesepaymentsbridge\/payorder(withpayload:fromscheme:callback:)"},"doc://jp.elestyle.Elepay/documentation/ElepaySDK/ElepayChinesePaymentsBridge/processAuth_V2Result(withResultUrl:standbyCallback:)":{"role":"symbol","title":"processAuth_V2Result(withResultUrl:standbyCallback:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"processAuth_V2Result"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withResultUrl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"standbyCallback"},{"kind":"text","text":": (["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayChinesePaymentsBridge\/processAuth_V2Result(withResultUrl:standbyCallback:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"processAuth_V2ResultWithResultUrl:standbyCallback:"}],"url":"\/documentation\/elepaysdk\/elepaychinesepaymentsbridge\/processauth_v2result(withresulturl:standbycallback:)"},"doc://jp.elestyle.Elepay/documentation/ElepaySDK/ElepayChinesePaymentsBridge/isUPAppInstalled()":{"role":"symbol","title":"isUPAppInstalled()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isUPAppInstalled"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayChinesePaymentsBridge\/isUPAppInstalled()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isUPAppInstalled"}],"url":"\/documentation\/elepaysdk\/elepaychinesepaymentsbridge\/isupappinstalled()"},"doc://jp.elestyle.Elepay/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/jp.elestyle.Elepay\/SQ"},"doc://jp.elestyle.Elepay/documentation/ElepaySDK/StripeBridgeCardValidationState":{"role":"symbol","title":"StripeBridgeCardValidationState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"StripeBridgeCardValidationState"}],"abstract":[],"identifier":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/StripeBridgeCardValidationState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StripeBridgeCardValidationState"}],"url":"\/documentation\/elepaysdk\/stripebridgecardvalidationstate"},"doc://jp.elestyle.Elepay/documentation/ElepaySDK/ElepayChinesePaymentsBridge/processOrder(withPaymentResult:standbyCallback:)":{"role":"symbol","title":"processOrder(withPaymentResult:standbyCallback:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"processOrder"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withPaymentResult"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"standbyCallback"},{"kind":"text","text":": (["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayChinesePaymentsBridge\/processOrder(withPaymentResult:standbyCallback:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"processOrderWithPaymentResult:standbyCallback:"}],"url":"\/documentation\/elepaysdk\/elepaychinesepaymentsbridge\/processorder(withpaymentresult:standbycallback:)"},"doc://jp.elestyle.Elepay/documentation/ElepaySDK/ElepayChinesePaymentsBridge/handleWXOpenUniversalLink(_:)":{"role":"symbol","title":"handleWXOpenUniversalLink(_:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handleWXOpenUniversalLink"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSUserActivity","preciseIdentifier":"c:objc(cs)NSUserActivity"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayChinesePaymentsBridge\/handleWXOpenUniversalLink(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"handleWXOpenUniversalLink:"}],"url":"\/documentation\/elepaysdk\/elepaychinesepaymentsbridge\/handlewxopenuniversallink(_:)"},"doc://jp.elestyle.Elepay/documentation/ElepaySDK/ElepayRPayBridge":{"role":"symbol","title":"ElepayRPayBridge","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ElepayRPayBridge"}],"abstract":[],"identifier":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayRPayBridge","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ElepayRPayBridge"}],"url":"\/documentation\/elepaysdk\/elepayrpaybridge"},"doc://jp.elestyle.Elepay/documentation/ElepaySDK/ElepayChinesePaymentsBridge/isUnionPaySDKAvailable()":{"role":"symbol","title":"isUnionPaySDKAvailable()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isUnionPaySDKAvailable"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayChinesePaymentsBridge\/isUnionPaySDKAvailable()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isUnionPaySDKAvailable"}],"url":"\/documentation\/elepaysdk\/elepaychinesepaymentsbridge\/isunionpaysdkavailable()"},"doc://jp.elestyle.Elepay/documentation/ElepaySDK/ElepayChinesePaymentsBridge/handleUPOpen(_:complete:)":{"role":"symbol","title":"handleUPOpen(_:complete:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handleUPOpen"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"complete"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayChinesePaymentsBridge\/handleUPOpen(_:complete:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"handleUPOpenURL:completeBlock:"}],"url":"\/documentation\/elepaysdk\/elepaychinesepaymentsbridge\/handleupopen(_:complete:)"},"doc://jp.elestyle.Elepay/documentation/ElepaySDK/ElepayChinesePaymentsBridge/registerWXApp(_:universalLink:)":{"role":"symbol","title":"registerWXApp(_:universalLink:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"registerWXApp"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"universalLink"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayChinesePaymentsBridge\/registerWXApp(_:universalLink:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"registerWXApp:universalLink:"}],"url":"\/documentation\/elepaysdk\/elepaychinesepaymentsbridge\/registerwxapp(_:universallink:)"},"doc://jp.elestyle.Elepay/documentation/ElepaySDK/ElepayCardBridge":{"role":"symbol","title":"ElepayCardBridge","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ElepayCardBridge"}],"abstract":[],"identifier":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayCardBridge","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ElepayCardBridge"}],"url":"\/documentation\/elepaysdk\/elepaycardbridge"},"doc://jp.elestyle.Elepay/documentation/ElepaySDK/ElepayChinesePaymentsBridge/isWXAppInstalled()":{"role":"symbol","title":"isWXAppInstalled()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isWXAppInstalled"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayChinesePaymentsBridge\/isWXAppInstalled()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isWXAppInstalled"}],"url":"\/documentation\/elepaysdk\/elepaychinesepaymentsbridge\/iswxappinstalled()"},"doc://jp.elestyle.Elepay/documentation/ElepaySDK/ElepayStripeBridge":{"role":"symbol","title":"ElepayStripeBridge","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ElepayStripeBridge"}],"abstract":[],"identifier":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayStripeBridge","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ElepayStripeBridge"}],"url":"\/documentation\/elepaysdk\/elepaystripebridge"},"doc://jp.elestyle.Elepay/documentation/ElepaySDK/ElepayChinesePaymentsBridge/isWechatPayAvailable()":{"role":"symbol","title":"isWechatPayAvailable()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isWechatPayAvailable"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayChinesePaymentsBridge\/isWechatPayAvailable()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isWechatPayAvailable"}],"url":"\/documentation\/elepaysdk\/elepaychinesepaymentsbridge\/iswechatpayavailable()"},"doc://jp.elestyle.Elepay/documentation/ElepaySDK/StripeBridgePaymentStatus":{"role":"symbol","title":"StripeBridgePaymentStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"StripeBridgePaymentStatus"}],"abstract":[],"identifier":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/StripeBridgePaymentStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StripeBridgePaymentStatus"}],"url":"\/documentation\/elepaysdk\/stripebridgepaymentstatus"},"doc://jp.elestyle.Elepay/documentation/ElepaySDK/ElepayChinesePaymentsBridge/startUPPayment(_:fromScheme:mode:viewController:)":{"role":"symbol","title":"startUPPayment(_:fromScheme:mode:viewController:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startUPPayment"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"fromScheme"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"viewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayChinesePaymentsBridge\/startUPPayment(_:fromScheme:mode:viewController:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startUPPayment:fromScheme:mode:viewController:"}],"url":"\/documentation\/elepaysdk\/elepaychinesepaymentsbridge\/startuppayment(_:fromscheme:mode:viewcontroller:)"},"doc://jp.elestyle.Elepay/documentation/ElepaySDK/ApplePayContextDelegateBridge":{"role":"symbol","title":"ApplePayContextDelegateBridge","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ApplePayContextDelegateBridge"}],"abstract":[],"identifier":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ApplePayContextDelegateBridge","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ApplePayContextDelegateBridge"}],"url":"\/documentation\/elepaysdk\/applepaycontextdelegatebridge"},"doc://jp.elestyle.Elepay/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/jp.elestyle.Elepay\/objc(cs)NSObject"},"doc://jp.elestyle.Elepay/documentation/ElepaySDK/ElepayChinesePaymentsBridge/pay(_:mode:scheme:viewController:onResult:)":{"role":"symbol","title":"pay(_:mode:scheme:viewController:onResult:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pay"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"scheme"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"viewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onResult"},{"kind":"text","text":": (["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayChinesePaymentsBridge\/pay(_:mode:scheme:viewController:onResult:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"pay:mode:scheme:viewController:onResult:"}],"url":"\/documentation\/elepaysdk\/elepaychinesepaymentsbridge\/pay(_:mode:scheme:viewcontroller:onresult:)"},"doc://jp.elestyle.Elepay/documentation/ElepaySDK/ElepayChinesePaymentsBridge/isAlipayAvailable()":{"role":"symbol","title":"isAlipayAvailable()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isAlipayAvailable"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayChinesePaymentsBridge\/isAlipayAvailable()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isAlipayAvailable"}],"url":"\/documentation\/elepaysdk\/elepaychinesepaymentsbridge\/isalipayavailable()"},"doc://jp.elestyle.Elepay/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/jp.elestyle.Elepay\/objc(pl)NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ElepayChinesePaymentsBridge"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ElepayChinesePaymentsBridge"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ElepayChinesePaymentsBridge"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Type Methods","identifiers":["doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayChinesePaymentsBridge\/handleUPOpen(_:complete:)","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayChinesePaymentsBridge\/handleWXOpen(_:)","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayChinesePaymentsBridge\/handleWXOpenUniversalLink(_:)","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayChinesePaymentsBridge\/isAlipayAvailable()","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayChinesePaymentsBridge\/isAllpaySDKAvailable()","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayChinesePaymentsBridge\/isUPAppInstalled()","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayChinesePaymentsBridge\/isUnionPaySDKAvailable()","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayChinesePaymentsBridge\/isWXAppInstalled()","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayChinesePaymentsBridge\/isWXAppSupportAPI()","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayChinesePaymentsBridge\/isWechatPayAvailable()","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayChinesePaymentsBridge\/makeWXPayment(_:callback:)","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayChinesePaymentsBridge\/open(_:)","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayChinesePaymentsBridge\/pay(_:mode:scheme:viewController:onResult:)","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayChinesePaymentsBridge\/payOrder(withPayload:fromScheme:callback:)","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayChinesePaymentsBridge\/processAuth_V2Result(withResultUrl:standbyCallback:)","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayChinesePaymentsBridge\/processOrder(withPaymentResult:standbyCallback:)","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayChinesePaymentsBridge\/registerWXApp(_:universalLink:)","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayChinesePaymentsBridge\/startUPPayment(_:fromScheme:mode:viewController:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/jp.elestyle.Elepay\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"3rd party framework bridge","identifiers":["doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayStripeBridge","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/StripeBridgeCardValidationState","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/StripeBridgePaymentStatus","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayRPayBridge","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayCardBridge","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ApplePayContextDelegateBridge"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ElepayChinesePaymentsBridge"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayChinesePaymentsBridge~1handleWXOpen(_:)\/title","value":"handleWXOpenURL:"},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayChinesePaymentsBridge~1handleWXOpen(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"handleWXOpenURL:"}]},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayChinesePaymentsBridge~1isWXAppSupportAPI()\/title","value":"isWXAppSupportAPI"},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayChinesePaymentsBridge~1isWXAppSupportAPI()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"isWXAppSupportAPI"}]},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayChinesePaymentsBridge~1makeWXPayment(_:callback:)\/title","value":"makeWXPayment:callback:"},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayChinesePaymentsBridge~1makeWXPayment(_:callback:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"makeWXPayment:callback:"}]},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayChinesePaymentsBridge\/title","value":"ElepayChinesePaymentsBridge"},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayChinesePaymentsBridge\/fragments","value":[{"kind":"identifier","text":"ElepayChinesePaymentsBridge"}]},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayChinesePaymentsBridge~1isAllpaySDKAvailable()\/title","value":"isAllpaySDKAvailable"},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayChinesePaymentsBridge~1isAllpaySDKAvailable()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"isAllpaySDKAvailable"}]},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayChinesePaymentsBridge~1open(_:)\/title","value":"openURL:"},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayChinesePaymentsBridge~1open(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"openURL:"}]},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayChinesePaymentsBridge~1payOrder(withPayload:fromScheme:callback:)\/title","value":"payOrderWithPayload:fromScheme:callback:"},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayChinesePaymentsBridge~1payOrder(withPayload:fromScheme:callback:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"payOrderWithPayload:fromScheme:callback:"}]},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayChinesePaymentsBridge~1processAuth_V2Result(withResultUrl:standbyCallback:)\/title","value":"processAuth_V2ResultWithResultUrl:standbyCallback:"},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayChinesePaymentsBridge~1processAuth_V2Result(withResultUrl:standbyCallback:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"processAuth_V2ResultWithResultUrl:standbyCallback:"}]},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayChinesePaymentsBridge~1isUPAppInstalled()\/title","value":"isUPAppInstalled"},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayChinesePaymentsBridge~1isUPAppInstalled()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"isUPAppInstalled"}]},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1StripeBridgeCardValidationState\/title","value":"StripeBridgeCardValidationState"},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1StripeBridgeCardValidationState\/fragments","value":[{"kind":"identifier","text":"StripeBridgeCardValidationState"}]},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayChinesePaymentsBridge~1processOrder(withPaymentResult:standbyCallback:)\/title","value":"processOrderWithPaymentResult:standbyCallback:"},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayChinesePaymentsBridge~1processOrder(withPaymentResult:standbyCallback:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"processOrderWithPaymentResult:standbyCallback:"}]},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayChinesePaymentsBridge~1handleWXOpenUniversalLink(_:)\/title","value":"handleWXOpenUniversalLink:"},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayChinesePaymentsBridge~1handleWXOpenUniversalLink(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"handleWXOpenUniversalLink:"}]},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayRPayBridge\/title","value":"ElepayRPayBridge"},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayRPayBridge\/fragments","value":[{"kind":"identifier","text":"ElepayRPayBridge"}]},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayChinesePaymentsBridge~1isUnionPaySDKAvailable()\/title","value":"isUnionPaySDKAvailable"},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayChinesePaymentsBridge~1isUnionPaySDKAvailable()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"isUnionPaySDKAvailable"}]},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayChinesePaymentsBridge~1handleUPOpen(_:complete:)\/title","value":"handleUPOpenURL:completeBlock:"},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayChinesePaymentsBridge~1handleUPOpen(_:complete:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"handleUPOpenURL:completeBlock:"}]},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayChinesePaymentsBridge~1registerWXApp(_:universalLink:)\/title","value":"registerWXApp:universalLink:"},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayChinesePaymentsBridge~1registerWXApp(_:universalLink:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"registerWXApp:universalLink:"}]},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayCardBridge\/title","value":"ElepayCardBridge"},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayCardBridge\/fragments","value":[{"kind":"identifier","text":"ElepayCardBridge"}]},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayChinesePaymentsBridge~1isWXAppInstalled()\/title","value":"isWXAppInstalled"},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayChinesePaymentsBridge~1isWXAppInstalled()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"isWXAppInstalled"}]},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayStripeBridge\/title","value":"ElepayStripeBridge"},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayStripeBridge\/fragments","value":[{"kind":"identifier","text":"ElepayStripeBridge"}]},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayChinesePaymentsBridge~1isWechatPayAvailable()\/title","value":"isWechatPayAvailable"},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayChinesePaymentsBridge~1isWechatPayAvailable()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"isWechatPayAvailable"}]},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1StripeBridgePaymentStatus\/title","value":"StripeBridgePaymentStatus"},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1StripeBridgePaymentStatus\/fragments","value":[{"kind":"identifier","text":"StripeBridgePaymentStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayChinesePaymentsBridge~1startUPPayment(_:fromScheme:mode:viewController:)\/title","value":"startUPPayment:fromScheme:mode:viewController:"},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayChinesePaymentsBridge~1startUPPayment(_:fromScheme:mode:viewController:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"startUPPayment:fromScheme:mode:viewController:"}]},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ApplePayContextDelegateBridge\/title","value":"ApplePayContextDelegateBridge"},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ApplePayContextDelegateBridge\/fragments","value":[{"kind":"identifier","text":"ApplePayContextDelegateBridge"}]},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayChinesePaymentsBridge~1pay(_:mode:scheme:viewController:onResult:)\/title","value":"pay:mode:scheme:viewController:onResult:"},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayChinesePaymentsBridge~1pay(_:mode:scheme:viewController:onResult:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"pay:mode:scheme:viewController:onResult:"}]},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayChinesePaymentsBridge~1isAlipayAvailable()\/title","value":"isAlipayAvailable"},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayChinesePaymentsBridge~1isAlipayAvailable()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"isAlipayAvailable"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}