{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"StripeBridgeCardValidationState"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/elepaysdk\/stripebridgecardvalidationstate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/elepaysdk\/stripebridgecardvalidationstate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/jp.elestyle.Elepay\/SQ","doc:\/\/jp.elestyle.Elepay\/SH","doc:\/\/jp.elestyle.Elepay\/SY","doc:\/\/jp.elestyle.Elepay\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/StripeBridgeCardValidationState","interfaceLanguage":"swift"},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/StripeBridgeCardValidationState\/incomplete","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/StripeBridgeCardValidationState\/invalid","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/StripeBridgeCardValidationState\/valid"]},{"title":"Initializers","identifiers":["doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/StripeBridgeCardValidationState\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/StripeBridgeCardValidationState\/Equatable-Implementations","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/StripeBridgeCardValidationState\/RawRepresentable-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"StripeBridgeCardValidationState"}],"title":"StripeBridgeCardValidationState","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@StripeBridgeCardValidationState","modules":[{"name":"ElepaySDK"}],"navigatorTitle":[{"kind":"identifier","text":"StripeBridgeCardValidationState"}]},"hierarchy":{"paths":[["doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK"]]},"seeAlsoSections":[{"title":"3rd party framework bridge","identifiers":["doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayChinesePaymentsBridge","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayStripeBridge","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/StripeBridgePaymentStatus","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayRPayBridge","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayCardBridge","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ApplePayContextDelegateBridge"],"generated":true}],"references":{"doc://jp.elestyle.Elepay/documentation/ElepaySDK/ElepayStripeBridge":{"role":"symbol","title":"ElepayStripeBridge","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ElepayStripeBridge"}],"abstract":[],"identifier":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayStripeBridge","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ElepayStripeBridge"}],"url":"\/documentation\/elepaysdk\/elepaystripebridge"},"doc://jp.elestyle.Elepay/documentation/ElepaySDK/StripeBridgeCardValidationState/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/StripeBridgeCardValidationState\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/elepaysdk\/stripebridgecardvalidationstate\/equatable-implementations"},"doc://jp.elestyle.Elepay/documentation/ElepaySDK/ElepayCardBridge":{"role":"symbol","title":"ElepayCardBridge","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ElepayCardBridge"}],"abstract":[],"identifier":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayCardBridge","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ElepayCardBridge"}],"url":"\/documentation\/elepaysdk\/elepaycardbridge"},"doc://jp.elestyle.Elepay/documentation/ElepaySDK":{"role":"collection","title":"ElepaySDK","abstract":[{"type":"text","text":"elepay SDK for iOS is made for your iOS \/ iPad OS Apps to easily import elepay multi-payment platform."}],"identifier":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK","kind":"symbol","type":"topic","url":"\/documentation\/elepaysdk"},"doc://jp.elestyle.Elepay/documentation/ElepaySDK/StripeBridgeCardValidationState/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/StripeBridgeCardValidationState\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/elepaysdk\/stripebridgecardvalidationstate\/init(rawvalue:)"},"doc://jp.elestyle.Elepay/documentation/ElepaySDK/ElepayRPayBridge":{"role":"symbol","title":"ElepayRPayBridge","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ElepayRPayBridge"}],"abstract":[],"identifier":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayRPayBridge","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ElepayRPayBridge"}],"url":"\/documentation\/elepaysdk\/elepayrpaybridge"},"doc://jp.elestyle.Elepay/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/jp.elestyle.Elepay\/SH"},"doc://jp.elestyle.Elepay/documentation/ElepaySDK/StripeBridgeCardValidationState/invalid":{"role":"symbol","title":"StripeBridgeCardValidationState.invalid","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalid"}],"abstract":[],"identifier":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/StripeBridgeCardValidationState\/invalid","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StripeBridgeCardValidationStateInvalid"}],"url":"\/documentation\/elepaysdk\/stripebridgecardvalidationstate\/invalid"},"doc://jp.elestyle.Elepay/documentation/ElepaySDK/StripeBridgeCardValidationState/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/StripeBridgeCardValidationState\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/elepaysdk\/stripebridgecardvalidationstate\/rawrepresentable-implementations"},"doc://jp.elestyle.Elepay/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/jp.elestyle.Elepay\/s8SendableP"},"doc://jp.elestyle.Elepay/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/jp.elestyle.Elepay\/SY"},"doc://jp.elestyle.Elepay/documentation/ElepaySDK/StripeBridgePaymentStatus":{"role":"symbol","title":"StripeBridgePaymentStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"StripeBridgePaymentStatus"}],"abstract":[],"identifier":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/StripeBridgePaymentStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StripeBridgePaymentStatus"}],"url":"\/documentation\/elepaysdk\/stripebridgepaymentstatus"},"doc://jp.elestyle.Elepay/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/jp.elestyle.Elepay\/SQ"},"doc://jp.elestyle.Elepay/documentation/ElepaySDK/ElepayChinesePaymentsBridge":{"role":"symbol","title":"ElepayChinesePaymentsBridge","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ElepayChinesePaymentsBridge"}],"abstract":[],"identifier":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayChinesePaymentsBridge","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ElepayChinesePaymentsBridge"}],"url":"\/documentation\/elepaysdk\/elepaychinesepaymentsbridge"},"doc://jp.elestyle.Elepay/documentation/ElepaySDK/StripeBridgeCardValidationState":{"role":"symbol","title":"StripeBridgeCardValidationState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"StripeBridgeCardValidationState"}],"abstract":[],"identifier":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/StripeBridgeCardValidationState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StripeBridgeCardValidationState"}],"url":"\/documentation\/elepaysdk\/stripebridgecardvalidationstate"},"doc://jp.elestyle.Elepay/documentation/ElepaySDK/StripeBridgeCardValidationState/valid":{"role":"symbol","title":"StripeBridgeCardValidationState.valid","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"valid"}],"abstract":[],"identifier":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/StripeBridgeCardValidationState\/valid","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StripeBridgeCardValidationStateValid"}],"url":"\/documentation\/elepaysdk\/stripebridgecardvalidationstate\/valid"},"doc://jp.elestyle.Elepay/documentation/ElepaySDK/ApplePayContextDelegateBridge":{"role":"symbol","title":"ApplePayContextDelegateBridge","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ApplePayContextDelegateBridge"}],"abstract":[],"identifier":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ApplePayContextDelegateBridge","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ApplePayContextDelegateBridge"}],"url":"\/documentation\/elepaysdk\/applepaycontextdelegatebridge"},"doc://jp.elestyle.Elepay/documentation/ElepaySDK/StripeBridgeCardValidationState/incomplete":{"role":"symbol","title":"StripeBridgeCardValidationState.incomplete","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"incomplete"}],"abstract":[],"identifier":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/StripeBridgeCardValidationState\/incomplete","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StripeBridgeCardValidationStateIncomplete"}],"url":"\/documentation\/elepaysdk\/stripebridgecardvalidationstate\/incomplete"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"StripeBridgeCardValidationState"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"StripeBridgeCardValidationState"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"StripeBridgeCardValidationState"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/StripeBridgeCardValidationState\/incomplete","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/StripeBridgeCardValidationState\/invalid","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/StripeBridgeCardValidationState\/valid"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"3rd party framework bridge","identifiers":["doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayChinesePaymentsBridge","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayStripeBridge","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/StripeBridgePaymentStatus","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayRPayBridge","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayCardBridge","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ApplePayContextDelegateBridge"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"StripeBridgeCardValidationState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayStripeBridge\/title","value":"ElepayStripeBridge"},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayStripeBridge\/fragments","value":[{"kind":"identifier","text":"ElepayStripeBridge"}]},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayCardBridge\/title","value":"ElepayCardBridge"},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayCardBridge\/fragments","value":[{"kind":"identifier","text":"ElepayCardBridge"}]},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayRPayBridge\/title","value":"ElepayRPayBridge"},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayRPayBridge\/fragments","value":[{"kind":"identifier","text":"ElepayRPayBridge"}]},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1StripeBridgeCardValidationState~1invalid\/title","value":"StripeBridgeCardValidationStateInvalid"},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1StripeBridgeCardValidationState~1invalid\/fragments","value":[{"kind":"identifier","text":"StripeBridgeCardValidationStateInvalid"}]},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1StripeBridgePaymentStatus\/title","value":"StripeBridgePaymentStatus"},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1StripeBridgePaymentStatus\/fragments","value":[{"kind":"identifier","text":"StripeBridgePaymentStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayChinesePaymentsBridge\/title","value":"ElepayChinesePaymentsBridge"},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayChinesePaymentsBridge\/fragments","value":[{"kind":"identifier","text":"ElepayChinesePaymentsBridge"}]},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1StripeBridgeCardValidationState\/title","value":"StripeBridgeCardValidationState"},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1StripeBridgeCardValidationState\/fragments","value":[{"kind":"identifier","text":"StripeBridgeCardValidationState"}]},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1StripeBridgeCardValidationState~1valid\/title","value":"StripeBridgeCardValidationStateValid"},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1StripeBridgeCardValidationState~1valid\/fragments","value":[{"kind":"identifier","text":"StripeBridgeCardValidationStateValid"}]},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ApplePayContextDelegateBridge\/title","value":"ApplePayContextDelegateBridge"},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ApplePayContextDelegateBridge\/fragments","value":[{"kind":"identifier","text":"ApplePayContextDelegateBridge"}]},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1StripeBridgeCardValidationState~1incomplete\/title","value":"StripeBridgeCardValidationStateIncomplete"},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1StripeBridgeCardValidationState~1incomplete\/fragments","value":[{"kind":"identifier","text":"StripeBridgeCardValidationStateIncomplete"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}