{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"valid"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/elepaysdk\/stripebridgecardvalidationstate\/valid"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/elepaysdk\/stripebridgecardvalidationstate\/valid"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/StripeBridgeCardValidationState\/valid","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"valid"}],"title":"StripeBridgeCardValidationState.valid","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@StripeBridgeCardValidationState@StripeBridgeCardValidationStateValid","modules":[{"name":"ElepaySDK"}],"navigatorTitle":[{"kind":"identifier","text":"StripeBridgeCardValidationStateValid"}]},"hierarchy":{"paths":[["doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/StripeBridgeCardValidationState"]]},"references":{"doc://jp.elestyle.Elepay/documentation/ElepaySDK/StripeBridgeCardValidationState/valid":{"role":"symbol","title":"StripeBridgeCardValidationState.valid","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"valid"}],"abstract":[],"identifier":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/StripeBridgeCardValidationState\/valid","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StripeBridgeCardValidationStateValid"}],"url":"\/documentation\/elepaysdk\/stripebridgecardvalidationstate\/valid"},"doc://jp.elestyle.Elepay/documentation/ElepaySDK":{"role":"collection","title":"ElepaySDK","abstract":[{"type":"text","text":"elepay SDK for iOS is made for your iOS \/ iPad OS Apps to easily import elepay multi-payment platform."}],"identifier":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK","kind":"symbol","type":"topic","url":"\/documentation\/elepaysdk"},"doc://jp.elestyle.Elepay/documentation/ElepaySDK/StripeBridgeCardValidationState":{"role":"symbol","title":"StripeBridgeCardValidationState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"StripeBridgeCardValidationState"}],"abstract":[],"identifier":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/StripeBridgeCardValidationState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StripeBridgeCardValidationState"}],"url":"\/documentation\/elepaysdk\/stripebridgecardvalidationstate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"StripeBridgeCardValidationStateValid"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"StripeBridgeCardValidationStateValid"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"StripeBridgeCardValidationStateValid"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1StripeBridgeCardValidationState~1valid\/title","value":"StripeBridgeCardValidationStateValid"},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1StripeBridgeCardValidationState~1valid\/fragments","value":[{"kind":"identifier","text":"StripeBridgeCardValidationStateValid"}]},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1StripeBridgeCardValidationState\/title","value":"StripeBridgeCardValidationState"},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1StripeBridgeCardValidationState\/fragments","value":[{"kind":"identifier","text":"StripeBridgeCardValidationState"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}