{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pluginDeviceSupportsApplePay"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/elepaysdk\/elepaystripebridge\/plugindevicesupportsapplepay()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/elepaysdk\/elepaystripebridge\/plugindevicesupportsapplepay()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayStripeBridge\/pluginDeviceSupportsApplePay()","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pluginDeviceSupportsApplePay"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"pluginDeviceSupportsApplePay()","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)ElepayStripeBridge(cm)pluginDeviceSupportsApplePay","modules":[{"name":"ElepaySDK"}],"navigatorTitle":[{"kind":"identifier","text":"pluginDeviceSupportsApplePay"}]},"hierarchy":{"paths":[["doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayStripeBridge"]]},"references":{"doc://jp.elestyle.Elepay/documentation/ElepaySDK/ElepayStripeBridge":{"role":"symbol","title":"ElepayStripeBridge","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ElepayStripeBridge"}],"abstract":[],"identifier":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayStripeBridge","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ElepayStripeBridge"}],"url":"\/documentation\/elepaysdk\/elepaystripebridge"},"doc://jp.elestyle.Elepay/documentation/ElepaySDK/ElepayStripeBridge/pluginDeviceSupportsApplePay()":{"role":"symbol","title":"pluginDeviceSupportsApplePay()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pluginDeviceSupportsApplePay"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayStripeBridge\/pluginDeviceSupportsApplePay()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"pluginDeviceSupportsApplePay"}],"url":"\/documentation\/elepaysdk\/elepaystripebridge\/plugindevicesupportsapplepay()"},"doc://jp.elestyle.Elepay/documentation/ElepaySDK":{"role":"collection","title":"ElepaySDK","abstract":[{"type":"text","text":"elepay SDK for iOS is made for your iOS \/ iPad OS Apps to easily import elepay multi-payment platform."}],"identifier":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK","kind":"symbol","type":"topic","url":"\/documentation\/elepaysdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"pluginDeviceSupportsApplePay"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"pluginDeviceSupportsApplePay"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"pluginDeviceSupportsApplePay"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayStripeBridge\/title","value":"ElepayStripeBridge"},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayStripeBridge\/fragments","value":[{"kind":"identifier","text":"ElepayStripeBridge"}]},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayStripeBridge~1pluginDeviceSupportsApplePay()\/title","value":"pluginDeviceSupportsApplePay"},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayStripeBridge~1pluginDeviceSupportsApplePay()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"pluginDeviceSupportsApplePay"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}