{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pluginPaymentRequest"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withMerchantIdentifier"},{"kind":"text","text":" "},{"kind":"internalParam","text":"merchantIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"country"},{"kind":"text","text":" "},{"kind":"internalParam","text":"countryCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"currency"},{"kind":"text","text":" "},{"kind":"internalParam","text":"currencyCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"PKPaymentRequest","preciseIdentifier":"c:objc(cs)PKPaymentRequest"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/elepaysdk\/elepaystripebridge\/pluginpaymentrequest(withmerchantidentifier:country:currency:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/elepaysdk\/elepaystripebridge\/pluginpaymentrequest(withmerchantidentifier:country:currency:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayStripeBridge\/pluginPaymentRequest(withMerchantIdentifier:country:currency:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pluginPaymentRequest"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withMerchantIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"country"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"currency"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"PKPaymentRequest","preciseIdentifier":"c:objc(cs)PKPaymentRequest"}],"title":"pluginPaymentRequest(withMerchantIdentifier:country:currency:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)ElepayStripeBridge(cm)pluginPaymentRequestWithMerchantIdentifier:country:currency:","modules":[{"name":"ElepaySDK"}],"navigatorTitle":[{"kind":"identifier","text":"pluginPaymentRequestWithMerchantIdentifier:country:currency:"}]},"hierarchy":{"paths":[["doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayStripeBridge"]]},"references":{"doc://jp.elestyle.Elepay/documentation/ElepaySDK/ElepayStripeBridge/pluginPaymentRequest(withMerchantIdentifier:country:currency:)":{"role":"symbol","title":"pluginPaymentRequest(withMerchantIdentifier:country:currency:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pluginPaymentRequest"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withMerchantIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"country"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"currency"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"PKPaymentRequest","preciseIdentifier":"c:objc(cs)PKPaymentRequest"}],"abstract":[],"identifier":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayStripeBridge\/pluginPaymentRequest(withMerchantIdentifier:country:currency:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"pluginPaymentRequestWithMerchantIdentifier:country:currency:"}],"url":"\/documentation\/elepaysdk\/elepaystripebridge\/pluginpaymentrequest(withmerchantidentifier:country:currency:)"},"doc://jp.elestyle.Elepay/documentation/ElepaySDK":{"role":"collection","title":"ElepaySDK","abstract":[{"type":"text","text":"elepay SDK for iOS is made for your iOS \/ iPad OS Apps to easily import elepay multi-payment platform."}],"identifier":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK","kind":"symbol","type":"topic","url":"\/documentation\/elepaysdk"},"doc://jp.elestyle.Elepay/documentation/ElepaySDK/ElepayStripeBridge":{"role":"symbol","title":"ElepayStripeBridge","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ElepayStripeBridge"}],"abstract":[],"identifier":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayStripeBridge","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ElepayStripeBridge"}],"url":"\/documentation\/elepaysdk\/elepaystripebridge"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"pluginPaymentRequestWithMerchantIdentifier:country:currency:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"pluginPaymentRequestWithMerchantIdentifier:country:currency:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"PKPaymentRequest","preciseIdentifier":"c:objc(cs)PKPaymentRequest"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"pluginPaymentRequestWithMerchantIdentifier:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"merchantIdentifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"country:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"countryCode"},{"kind":"text","text":" "},{"kind":"identifier","text":"currency:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"currencyCode"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayStripeBridge~1pluginPaymentRequest(withMerchantIdentifier:country:currency:)\/title","value":"pluginPaymentRequestWithMerchantIdentifier:country:currency:"},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayStripeBridge~1pluginPaymentRequest(withMerchantIdentifier:country:currency:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"pluginPaymentRequestWithMerchantIdentifier:country:currency:"}]},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayStripeBridge\/title","value":"ElepayStripeBridge"},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayStripeBridge\/fragments","value":[{"kind":"identifier","text":"ElepayStripeBridge"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}