{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"safeApplePayPluginClass"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"AnyClass","preciseIdentifier":"s:s8AnyClassa"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/elepaysdk\/elepaystripebridge\/safeapplepaypluginclass()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/elepaysdk\/elepaystripebridge\/safeapplepaypluginclass()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayStripeBridge\/safeApplePayPluginClass()","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"safeApplePayPluginClass"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"AnyClass","preciseIdentifier":"s:s8AnyClassa"},{"kind":"text","text":"?"}],"title":"safeApplePayPluginClass()","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)ElepayStripeBridge(cm)safeApplePayPluginClass","modules":[{"name":"ElepaySDK"}],"navigatorTitle":[{"kind":"identifier","text":"safeApplePayPluginClass"}]},"hierarchy":{"paths":[["doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayStripeBridge"]]},"references":{"doc://jp.elestyle.Elepay/documentation/ElepaySDK":{"role":"collection","title":"ElepaySDK","abstract":[{"type":"text","text":"elepay SDK for iOS is made for your iOS \/ iPad OS Apps to easily import elepay multi-payment platform."}],"identifier":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK","kind":"symbol","type":"topic","url":"\/documentation\/elepaysdk"},"doc://jp.elestyle.Elepay/documentation/ElepaySDK/ElepayStripeBridge":{"role":"symbol","title":"ElepayStripeBridge","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ElepayStripeBridge"}],"abstract":[],"identifier":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayStripeBridge","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ElepayStripeBridge"}],"url":"\/documentation\/elepaysdk\/elepaystripebridge"},"doc://jp.elestyle.Elepay/documentation/ElepaySDK/ElepayStripeBridge/safeApplePayPluginClass()":{"role":"symbol","title":"safeApplePayPluginClass()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"safeApplePayPluginClass"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"AnyClass","preciseIdentifier":"s:s8AnyClassa"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayStripeBridge\/safeApplePayPluginClass()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"safeApplePayPluginClass"}],"url":"\/documentation\/elepaysdk\/elepaystripebridge\/safeapplepaypluginclass()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"safeApplePayPluginClass"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"safeApplePayPluginClass"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"Class","preciseIdentifier":"c:*QO"},{"kind":"text","text":") "},{"kind":"identifier","text":"safeApplePayPluginClass"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayStripeBridge\/title","value":"ElepayStripeBridge"},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayStripeBridge\/fragments","value":[{"kind":"identifier","text":"ElepayStripeBridge"}]},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayStripeBridge~1safeApplePayPluginClass()\/title","value":"safeApplePayPluginClass"},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayStripeBridge~1safeApplePayPluginClass()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"safeApplePayPluginClass"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}