{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isWechatPayAvailable"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/elepaysdk\/elepaychinesepaymentsbridge\/iswechatpayavailable()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/elepaysdk\/elepaychinesepaymentsbridge\/iswechatpayavailable()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayChinesePaymentsBridge\/isWechatPayAvailable()","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isWechatPayAvailable"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"isWechatPayAvailable()","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)ElepayChinesePaymentsBridge(cm)isWechatPayAvailable","modules":[{"name":"ElepaySDK"}],"navigatorTitle":[{"kind":"identifier","text":"isWechatPayAvailable"}]},"hierarchy":{"paths":[["doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayChinesePaymentsBridge"]]},"references":{"doc://jp.elestyle.Elepay/documentation/ElepaySDK/ElepayChinesePaymentsBridge":{"role":"symbol","title":"ElepayChinesePaymentsBridge","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ElepayChinesePaymentsBridge"}],"abstract":[],"identifier":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayChinesePaymentsBridge","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ElepayChinesePaymentsBridge"}],"url":"\/documentation\/elepaysdk\/elepaychinesepaymentsbridge"},"doc://jp.elestyle.Elepay/documentation/ElepaySDK/ElepayChinesePaymentsBridge/isWechatPayAvailable()":{"role":"symbol","title":"isWechatPayAvailable()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isWechatPayAvailable"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayChinesePaymentsBridge\/isWechatPayAvailable()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isWechatPayAvailable"}],"url":"\/documentation\/elepaysdk\/elepaychinesepaymentsbridge\/iswechatpayavailable()"},"doc://jp.elestyle.Elepay/documentation/ElepaySDK":{"role":"collection","title":"ElepaySDK","abstract":[{"type":"text","text":"elepay SDK for iOS is made for your iOS \/ iPad OS Apps to easily import elepay multi-payment platform."}],"identifier":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK","kind":"symbol","type":"topic","url":"\/documentation\/elepaysdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"isWechatPayAvailable"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"isWechatPayAvailable"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"isWechatPayAvailable"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayChinesePaymentsBridge\/title","value":"ElepayChinesePaymentsBridge"},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayChinesePaymentsBridge\/fragments","value":[{"kind":"identifier","text":"ElepayChinesePaymentsBridge"}]},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayChinesePaymentsBridge~1isWechatPayAvailable()\/title","value":"isWechatPayAvailable"},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayChinesePaymentsBridge~1isWechatPayAvailable()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"isWechatPayAvailable"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}