{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startUPPayment"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"tn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"fromScheme"},{"kind":"text","text":" "},{"kind":"internalParam","text":"scheme"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"viewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/elepaysdk\/elepaychinesepaymentsbridge\/startuppayment(_:fromscheme:mode:viewcontroller:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/elepaysdk\/elepaychinesepaymentsbridge\/startuppayment(_:fromscheme:mode:viewcontroller:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayChinesePaymentsBridge\/startUPPayment(_:fromScheme:mode:viewController:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startUPPayment"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"fromScheme"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"viewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"startUPPayment(_:fromScheme:mode:viewController:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)ElepayChinesePaymentsBridge(cm)startUPPayment:fromScheme:mode:viewController:","modules":[{"name":"ElepaySDK"}],"navigatorTitle":[{"kind":"identifier","text":"startUPPayment:fromScheme:mode:viewController:"}]},"hierarchy":{"paths":[["doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK","doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayChinesePaymentsBridge"]]},"references":{"doc://jp.elestyle.Elepay/documentation/ElepaySDK/ElepayChinesePaymentsBridge":{"role":"symbol","title":"ElepayChinesePaymentsBridge","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ElepayChinesePaymentsBridge"}],"abstract":[],"identifier":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayChinesePaymentsBridge","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ElepayChinesePaymentsBridge"}],"url":"\/documentation\/elepaysdk\/elepaychinesepaymentsbridge"},"doc://jp.elestyle.Elepay/documentation/ElepaySDK":{"role":"collection","title":"ElepaySDK","abstract":[{"type":"text","text":"elepay SDK for iOS is made for your iOS \/ iPad OS Apps to easily import elepay multi-payment platform."}],"identifier":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK","kind":"symbol","type":"topic","url":"\/documentation\/elepaysdk"},"doc://jp.elestyle.Elepay/documentation/ElepaySDK/ElepayChinesePaymentsBridge/startUPPayment(_:fromScheme:mode:viewController:)":{"role":"symbol","title":"startUPPayment(_:fromScheme:mode:viewController:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startUPPayment"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"fromScheme"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"viewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/jp.elestyle.Elepay\/documentation\/ElepaySDK\/ElepayChinesePaymentsBridge\/startUPPayment(_:fromScheme:mode:viewController:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startUPPayment:fromScheme:mode:viewController:"}],"url":"\/documentation\/elepaysdk\/elepaychinesepaymentsbridge\/startuppayment(_:fromscheme:mode:viewcontroller:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"startUPPayment:fromScheme:mode:viewController:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"startUPPayment:fromScheme:mode:viewController:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"startUPPayment:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"tn"},{"kind":"text","text":" "},{"kind":"identifier","text":"fromScheme:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"scheme"},{"kind":"text","text":" "},{"kind":"identifier","text":"mode:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"mode"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewController:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"viewController"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayChinesePaymentsBridge\/title","value":"ElepayChinesePaymentsBridge"},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayChinesePaymentsBridge\/fragments","value":[{"kind":"identifier","text":"ElepayChinesePaymentsBridge"}]},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayChinesePaymentsBridge~1startUPPayment(_:fromScheme:mode:viewController:)\/title","value":"startUPPayment:fromScheme:mode:viewController:"},{"op":"replace","path":"\/references\/doc:~1~1jp.elestyle.Elepay~1documentation~1ElepaySDK~1ElepayChinesePaymentsBridge~1startUPPayment(_:fromScheme:mode:viewController:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"startUPPayment:fromScheme:mode:viewController:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}